services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
      - ./ui/dist/metube/browser:/app/ui/dist/metube/browser:ro
      - ./app/main.py:/app/app/main.py:ro
    environment:
      - AUTH_ENABLED=true
      - AUTH_USERNAME=kuryshko
      - AUTH_PASSWORD=Cyberpunk2077!
      - AUTH_SESSION_TTL_SECONDS=86400
      - CHOWN_DIRS=false
